source "https://rubygems.org"

gem 'sinatra', '2.0.0.beta.2'
gem 'service_manager'

group :development do
    gem 'rspec', '3.10.0'
    gem 'cucumber', '5.2.0'
    gem 'capybara'
    gem 'launchy'
    gem 'childprocess'
end
